### ISSUE TITLE
CUBLAS ERROR while running example

### ISSUE THREAD

**Issue by ychuhp** [lucidrains/alphafold2#49]
When running the first example, prediction to distogram, I get the following error.
Is this error reproducible for you guys?
It looks like its crashing in the trunk part for the attention qkv remapping.

torch 1.8.0
cuda 10.2
python 3.6.9
 

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    msa_mask = msa_mask
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/af/alphafold2_pytorch/alphafold2.py", line 840, in forward
    msa_mask = msa_mask
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/af/alphafold2_pytorch/alphafold2.py", line 511, in forward
    x = attn(x, shape = seq_shape, mask = mask) + x
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/af/alphafold2_pytorch/alphafold2.py", line 45, in forward
    return self.fn(x, *args, **kwargs)
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/af/alphafold2_pytorch/alphafold2.py", line 107, in forward
    return attn(x, *args, shape = shape, mask = mask, **kwargs)
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/af/alphafold2_pytorch/alphafold2.py", line 411, in forward
    w_out = self.attn_width(w_x, mask = w_mask)
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/af/alphafold2_pytorch/alphafold2.py", line 235, in forward
    q, k, v = (self.to_q(x), *self.to_kv(context).chunk(2, dim = -1))
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ychnh/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)

RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```

**Comment by ychuhp** [comment]
It is running fine on the cpu.

**Comment by lucidrains** [comment]
@ychuhp it runs for me, i'm using python 3.7.3, torch version 1.7.1

**Comment by ychuhp** [comment]
Ok. I changed the torch version to 1.7.1 and it is working on the gpu.
What should be done with this information? I am new to github and I am not too sure of the procedures.

**Comment by lucidrains** [comment]
@ychuhp i've already registered it, will take care of this tomorrow - i haven't tried upgrading to torch 1.8 yet

**Comment by lucidrains** [comment]
@ychuhp of course, if you can figure it out, always welcome a PR :)

**Comment by ychuhp** [comment]
Ok. It is a non-issue.
My version of Cuda 10.2 is not compatible with torch 1.8.0
I will close this.

**Comment by lucidrains** [comment]
Oh I see! Got it

**Comment by lucidrains** [comment]
@ychuhp I'm actually running into the same issue trying to upgrade to torch 1.8, did you ever fix this? lol

**Comment by ychuhp** [comment]
I thought 1.8 was not with compatible with 10.2 (based on what I saw on the Install Pytorch menu at https://pytorch.org a couple of days ago)

I am having the same issue with 1.8
It is working fine with 1.7.1 and 1.9
Maybe there is an issue with the pytorch library.
